// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MovieAPIMovieAPIefcpt.Reverse;

public partial class MovieDetail
{
    public int MovieDetailsId { get; set; }

    public int Budget { get; set; }

    public string Synopsis { get; set; } = null!;

    public string Language { get; set; } = null!;

    public int MoviesId { get; set; }
}