// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace MovieAPI.Models;

public partial class Movie
{
    public int MoviesId { get; set; }

    public int Year { get; set; }

    public string Title { get; set; } = null!;

    public string Genre { get; set; } = null!;

    public TimeSpan Duration { get; set; }

    public int MovieDetailsId { get; set; }
}